# Generated by Django 3.1.6 on 2021-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='queId',
            field=models.IntegerField(),
        ),
    ]
